"""
PARAFAC traffic model — Python port of the MATLAB training scripts.

Replaces:
  models_allSeries_filtered_weekDays.m  -> mode "per_week"
  models_allSeries_filtered_allDays.m   -> mode "all_days"

Tensor structure: X[n_ud, 1440, 2]
  Axis 0: UD pairs  — each row is one (user, day) observation
  Axis 1: minutes   — 1440 time slots (00:00 … 23:59)
  Axis 2: direction — 0=download, 1=upload

Input CSVs (place in data/input/down/ and data/input/up/):
  One CSV per week, sorted alphabetically = week order.
  Format: user_id | day | 00:00 | 00:01 | ... | 23:59
  Generated by preprocess.py — no extra header row.

Output CSVs (written to data/output/<mode>/):
  modeA_<label>.csv  - UD pair loadings  (n_ud  x n_components)
  modeB_<label>.csv  - time loadings     (1440  x n_components)
  modeC_<label>.csv  - direction loading (2     x n_components)
  ids_ud_<label>.csv - user_id and day labels matching modeA rows

Usage:
  python train_model.py per_week
  python train_model.py all_days
  python train_model.py both --components 5 --tol 1e-8
"""

import argparse
import json
import os
import glob

import numpy as np
import pandas as pd
import tensorly as tl
from tensorly.decomposition import non_negative_parafac

try:
    import torch
    tl.set_backend("pytorch")
    torch.set_num_threads(torch.get_num_threads())
except ImportError:
    pass  # fall back to numpy backend

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# 5 components = the canonical "model5" reference (matlab/README.md, loadings_all.csv,
# validate_matlab.py). The older SUESTE_OLD/gigalink-processed/*.m scripts used 3;
# that line was superseded by the parafac_coronavirus model5. Override with --components.
NUM_COMP = 5
TOLERANCE = 1e-8
SEED = 123
NUM_MINUTES = 1440

_HERE = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(_HERE, "data")
DOWN_DIR = os.path.join(DATA_DIR, "input", "down")
UP_DIR = os.path.join(DATA_DIR, "input", "up")
OUTPUT_DIR = os.path.join(DATA_DIR, "output")


# ---------------------------------------------------------------------------
# Normalization — mirrors MATLAB nlog10.m
# ---------------------------------------------------------------------------

def nlog10(array: np.ndarray) -> np.ndarray:
    """log10(x + 1) — equivalent to MATLAB nlog10(array, 1)."""
    return np.log10(array + 1)


def nlog10_inverse(array: np.ndarray) -> np.ndarray:
    """Inverse: 10^x - 1 — equivalent to MATLAB nlog10(array, -1)."""
    return (10.0 ** array) - 1.0


# ---------------------------------------------------------------------------
# CSV loading
# ---------------------------------------------------------------------------

def load_week_csv(filepath: str):
    """
    Load one weekly traffic CSV produced by preprocess.py.

    Returns:
        ids  : DataFrame with columns ['user_id', 'day']
        data : ndarray of shape (n_ud, NUM_MINUTES)
    """
    df = pd.read_csv(filepath)
    ids = df.iloc[:, :2].copy()
    ids.columns = ["user_id", "day"]
    data = df.iloc[:, 2:].values.astype(float)
    return ids, data


# ---------------------------------------------------------------------------
# Tensor construction
# ---------------------------------------------------------------------------

def build_week_tensor(ids_down: pd.DataFrame, data_down: np.ndarray,
                      ids_up: pd.DataFrame, data_up: np.ndarray):
    """
    Build X[n_ud, 1440, 2] for one week.

    Intersects UD pairs present in both directions, then stacks down and up
    as the two slices along axis 2. Sorted intersection ensures reproducible
    row ordering across runs.

    Returns:
        X      : ndarray (n_ud, NUM_MINUTES, 2), log-normalized
        ids_ud : DataFrame with columns ['user_id', 'day'], one row per UD pair
    """
    keys_down = list(zip(ids_down["user_id"], ids_down["day"]))
    keys_up = list(zip(ids_up["user_id"], ids_up["day"]))

    common = sorted(set(keys_down) & set(keys_up))
    if not common:
        raise ValueError("No common UD pairs found between down and up files.")

    idx_down = {k: i for i, k in enumerate(keys_down)}
    idx_up = {k: i for i, k in enumerate(keys_up)}

    rows_down = [idx_down[k] for k in common]
    rows_up = [idx_up[k] for k in common]

    norm_down = nlog10(data_down[rows_down])
    norm_up = nlog10(data_up[rows_up])

    X = np.full((len(common), NUM_MINUTES, 2), np.nan)
    X[:, :, 0] = norm_down
    X[:, :, 1] = norm_up

    ids_ud = pd.DataFrame(common, columns=["user_id", "day"])
    print(f"  Intersection: {len(common)} UD pairs | Tensor shape: {X.shape}")
    return X, ids_ud


# ---------------------------------------------------------------------------
# PARAFAC
# ---------------------------------------------------------------------------

def run_parafac(X: np.ndarray, n_components: int = NUM_COMP,
                tol: float = TOLERANCE, seed: int = SEED,
                checkpoint_fn=None, checkpoint_every: int = 500):
    """
    Non-negative PARAFAC on a 3D tensor X[n_ud, 1440, 2].

    NaN entries are zeroed out and excluded from updates via a float mask
    (PyTorch does not support bool tensor arithmetic).

    If checkpoint_fn is provided, runs in chunks of checkpoint_every iterations
    and calls checkpoint_fn(cp) after each chunk — useful for long runs so
    results are available mid-training without waiting for full convergence.

    Always returns (cp, rec_errors, converged) — rec_errors is the
    per-iteration reconstruction-error trace tensorly recorded and converged
    says whether the fit actually reached `tol` or was cut off by
    n_iter_max, so callers can persist that instead of it only ever
    reaching stdout (see save_convergence).
    """
    nan_mask = np.isnan(X)
    tensor = tl.tensor(np.nan_to_num(X, nan=0.0))
    # Cast mask to float — PyTorch does not support arithmetic on bool tensors
    mask = tl.tensor((~nan_mask).astype(float)) if nan_mask.any() else None

    if checkpoint_fn is None:
        n_iter_max = 10000
        cp, rec_errors = non_negative_parafac(
            tensor,
            rank=n_components,
            n_iter_max=n_iter_max,
            tol=tol,
            random_state=seed,
            mask=mask,
            init="random",
            verbose=True,
            return_errors=True,
        )
        return cp, list(rec_errors), len(rec_errors) < n_iter_max

    # Chunked mode: run checkpoint_every iterations at a time, save after each.
    # No overall cap — the loop only exits once a chunk converges early, so
    # this path always ends "converged" (unlike the single-shot path above).
    cp = None
    total_iters = 0
    all_errors = []
    while True:
        cp, rec_errors = non_negative_parafac(
            tensor,
            rank=n_components,
            n_iter_max=checkpoint_every,
            tol=tol,
            random_state=seed if total_iters == 0 else None,
            mask=mask,
            init="random" if total_iters == 0 else cp,
            verbose=True,
            return_errors=True,
        )
        all_errors.extend(rec_errors)
        total_iters += len(rec_errors)
        print(f"  [checkpoint @ ~{total_iters} iters] saving...")
        checkpoint_fn(cp)
        if len(rec_errors) < checkpoint_every:
            print("  Converged.")
            break
    return cp, all_errors, True


# ---------------------------------------------------------------------------
# Output saving
# ---------------------------------------------------------------------------

def save_model(cp, label: str, ids_ud: pd.DataFrame, output_dir: str):
    """Save factor matrices and UD ID metadata as CSVs."""
    os.makedirs(output_dir, exist_ok=True)
    n_comp = cp.factors[0].shape[1]
    col_names = [f"final_model{i+1}" for i in range(n_comp)]

    for factor, mode in zip(cp.factors, ["modeA", "modeB", "modeC"]):
        path = os.path.join(output_dir, f"{mode}_{label}.csv")
        pd.DataFrame(factor, columns=col_names).to_csv(path, index=False)
        print(f"  Saved: {path}")

    ids_path = os.path.join(output_dir, f"ids_ud_{label}.csv")
    ids_ud.to_csv(ids_path, index=False)
    print(f"  Saved: {ids_path}")


def save_convergence(rec_errors, converged: bool, tol: float, label: str,
                     output_dir: str):
    """Persist the ALS convergence trace so it survives beyond stdout.

    Without this, whether a fit actually reached `tol` or was cut off by
    n_iter_max only ever existed as a `verbose=True` print statement — lost
    once the terminal/log scrolled past it, and unreadable at all while the
    process is still running and conda run is buffering stdout.
    """
    os.makedirs(output_dir, exist_ok=True)
    info = {
        "label": label,
        "tol": tol,
        "n_iter": len(rec_errors),
        "converged": converged,
        "final_error": float(rec_errors[-1]) if rec_errors else None,
        "final_improvement": (
            float(rec_errors[-2] - rec_errors[-1])
            if len(rec_errors) >= 2 else None
        ),
        "errors": [float(e) for e in rec_errors],
    }
    path = os.path.join(output_dir, f"convergence_{label}.json")
    with open(path, "w") as f:
        json.dump(info, f)
    status = "converged" if converged else "HIT n_iter_max — did not converge"
    print(f"  Saved: {path}  ({len(rec_errors)} iters, {status})")


# ---------------------------------------------------------------------------
# Training modes
# ---------------------------------------------------------------------------

def _load_week_pair(down_path: str, up_path: str):
    ids_down, data_down = load_week_csv(down_path)
    ids_up, data_up = load_week_csv(up_path)
    print(f"  Down: {len(ids_down)} rows | Up: {len(ids_up)} rows")
    return build_week_tensor(ids_down, data_down, ids_up, data_up)


def _get_file_pairs(down_dir: str, up_dir: str):
    down_files = sorted(glob.glob(os.path.join(down_dir, "*.csv")))
    up_files = sorted(glob.glob(os.path.join(up_dir, "*.csv")))
    if not down_files:
        raise FileNotFoundError(f"No CSV files found in {down_dir}")
    if len(down_files) != len(up_files):
        raise ValueError(
            f"Mismatch: {len(down_files)} down files vs {len(up_files)} up files"
        )
    return down_files, up_files


def train_per_week(output_base: str, n_components: int, tol: float,
                   down_dir: str = None, up_dir: str = None):
    """One independent PARAFAC model per week."""
    down_files, up_files = _get_file_pairs(down_dir or DOWN_DIR, up_dir or UP_DIR)

    for week_num, (down_path, up_path) in enumerate(zip(down_files, up_files), start=1):
        label = f"week{week_num:02d}"
        print(f"\n=== Week {week_num}: {os.path.basename(down_path)} ===")

        X, ids_ud = _load_week_pair(down_path, up_path)

        print(f"  Fitting PARAFAC (rank={n_components}, tol={tol})...")
        cp, rec_errors, converged = run_parafac(X, n_components=n_components, tol=tol)

        out_dir = os.path.join(output_base, "per_week", label)
        save_model(cp, label, ids_ud, out_dir)
        save_convergence(rec_errors, converged, tol, label, out_dir)


def train_all_days(output_base: str, n_components: int, tol: float,
                   checkpoint_every: int = 0,
                   down_dir: str = None, up_dir: str = None):
    """One PARAFAC model on all weeks combined (UD pairs concatenated)."""
    down_files, up_files = _get_file_pairs(down_dir or DOWN_DIR, up_dir or UP_DIR)

    all_X = []
    all_ids = []

    for week_num, (down_path, up_path) in enumerate(zip(down_files, up_files), start=1):
        print(f"\n--- Week {week_num}: {os.path.basename(down_path)} ---")
        X_week, ids_week = _load_week_pair(down_path, up_path)
        all_X.append(X_week)
        all_ids.append(ids_week)

    X_all = np.concatenate(all_X, axis=0)
    ids_all = pd.concat(all_ids, ignore_index=True).drop_duplicates().reset_index(drop=True)

    out_dir = os.path.join(output_base, "all_days")
    print(f"\n=== Fitting PARAFAC on full tensor {X_all.shape} "
          f"(rank={n_components}, tol={tol}) ===")

    checkpoint_fn = None
    if checkpoint_every > 0:
        def _save_checkpoint(cp):
            save_model(cp, "all_days", ids_all, out_dir)
        checkpoint_fn = _save_checkpoint

    cp, rec_errors, converged = run_parafac(
        X_all, n_components=n_components, tol=tol,
        checkpoint_fn=checkpoint_fn, checkpoint_every=checkpoint_every or 500)

    save_model(cp, "all_days", ids_all, out_dir)
    save_convergence(rec_errors, converged, tol, "all_days", out_dir)
    print("Done.")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Train PARAFAC on network traffic tensor data."
    )
    parser.add_argument(
        "mode",
        choices=["per_week", "all_days", "both"],
    )
    parser.add_argument(
        "--components", type=int, default=NUM_COMP,
        help=f"Number of PARAFAC components (default: {NUM_COMP})",
    )
    parser.add_argument(
        "--tol", type=float, default=TOLERANCE,
        help=f"Convergence tolerance (default: {TOLERANCE})",
    )
    parser.add_argument(
        "--output", default=OUTPUT_DIR,
        help=f"Base output directory (default: {OUTPUT_DIR})",
    )
    parser.add_argument(
        "--down-dir", default=DOWN_DIR,
        help=f"Directory with weekly download CSVs (default: {DOWN_DIR})",
    )
    parser.add_argument(
        "--up-dir", default=UP_DIR,
        help=f"Directory with weekly upload CSVs (default: {UP_DIR})",
    )
    parser.add_argument(
        "--checkpoint-every", type=int, default=0, metavar="N",
        help="Save factors every N iterations (0 = disabled, only save at convergence)",
    )
    args = parser.parse_args()

    if args.mode in ("per_week", "both"):
        print("\n====== PER-WEEK MODELS ======")
        train_per_week(args.output, args.components, args.tol,
                       down_dir=args.down_dir, up_dir=args.up_dir)

    if args.mode in ("all_days", "both"):
        print("\n====== ALL-DAYS MODEL ======")
        train_all_days(args.output, args.components, args.tol,
                       checkpoint_every=args.checkpoint_every,
                       down_dir=args.down_dir, up_dir=args.up_dir)


if __name__ == "__main__":
    main()
